name: Terraform workflow
on:
  workflow_call:
    inputs:
      TF_ACTION:
        required: true
        type: string
        default: plan
    secrets:
      TF_VAR_aws_access_key_id:
        required: true
      TF_VAR_aws_secret_access_key:
        required: true
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.6

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform plan
        if: inputs.TF_ACTION == 'plan'
        run: terraform plan

      - name: Terraform apply
        if: inputs.TF_ACTION == 'apply'
        run: terraform apply -auto-approve
